### ISSUE TITLE
feedburner link

### ISSUE THREAD

**Issue by romanyanke** [ikashkuta/ikashkuta.github.io#1]
твой [фидбернер](http://feeds.feedburner.com/kashkuta-ru) дает такую ссылку в рсс:
`http://kashkuta.ruhttp//kashkuta.ru/2016/01/11/new-post/`
вместо
`http://kashkuta.ru/2016/01/11/new-post/`

**Comment by ikashkuta** [comment]
И правда. Спасибо!
